version: '3'
services:
  eco-data-web:
    container_name: eco-data-web
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next