import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo ao <a href="#">Eco-Data!</a>
        </h1>

        <p className={styles.description}>
          Seu repositório para compartilhamento de pesquisas{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Acessar como pesquisador &rarr;</h2>
            <p>Faça login na plataforma para inserir seus dados de pesquisa</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Dados públicos &rarr;</h2>
            <p>tenha acesso aos dados de pesquisas disponíveis ao público em geral</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Quem somos ? &rarr;</h2>
            <p>Saiba mais sobre o projeto eco-data</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Entre em contato &rarr;</h2>
            <p>
              Entre em contato conosco através de nossos contatos
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
